"use client"

import React, { createContext, useContext, useState } from 'react'

export type Language = 'EN' | 'ES' | 'FR' | 'DE' | 'YO'

interface LanguageContextType {
    lang: Language
    setLang: (lang: Language) => void
    t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
    EN: {
        overview: "Overview",
        sources: "Sources",
        exports: "Export Center",
        library: "Knowledge Library",
        settings: "Settings",
        importSource: "Import Source",
        importFromDevice: "Import from Device",
        searchPlaceholder: "Search topics or paste a URL...",
        monitorSources: "Monitor sources, pipeline progress, and ready drafts.",
        recentSources: "Recent Sources",
        readyDrafts: "Ready Drafts",
        processingQueue: "Currently Processing",
        totalSources: "Total Sources",
        acceptedSources: "Accepted Sources",
        draftsReady: "Drafts Ready",
        viewAll: "View all",
        filter: "Filter",
        platform: "Platform",
        advanced: "Advanced",
        dateAdded: "Date Added",
        category: "Category",
        duration: "Duration",
        all: "All",
        processed: "Processed",
        processing: "Processing",
        unprocessed: "Unprocessed",
        run: "Run",
        export: "Export",
        decisionRationale: "Decision Rationale",
        generateEvaluate: "Generate Draft to Evaluate",
        pipelineExplanation: "Pipeline converts source to final draft, which is then scored blindly for insight density.",
        pipelineStages: "Pipeline Stages",
        processingLog: "Processing Log",
        allStagesComplete: "All pipeline stages complete.",
        sourceProcessed: "This source has been fully processed and exported.",
        briefExplanation: "This brief explicitly modifies how the LLM drafts and how the Editorial QA evaluates the piece.",
        resumePipeline: "Resume Pipeline",
        runPipelineToEvaluate: "Run the pipeline through 'Evaluate Draft' to generate a score.",
        score: "Draft Score",
        pending: "Pending",
        published: "Published",
        ingested: "Ingested",
        search: "Search",
        noSourcesFound: "No sources found",
        noSourcesDescription: "Try adjusting your filters or search query to find what you're looking for.",
        viewSources: "View Sources",
        quickImport: "Quick Import",
        dates: "Dates",
        actions: "Actions",
        today: "Today",
        yesterday: "Yesterday",
        last7Days: "Last 7 Days",
        qualScore: "QUAL SCORE"
    },
    ES: {
        overview: "Resumen",
        sources: "Fuentes",
        exports: "Centro de Exportación",
        library: "Biblioteca",
        settings: "Ajustes",
        importSource: "Importar Fuente",
        importFromDevice: "Importar desde dispositivo",
        searchPlaceholder: "Buscar temas o pegar URL...",
        monitorSources: "Monitorear fuentes, progreso y borradores.",
        recentSources: "Fuentes Recientes",
        readyDrafts: "Borradores Listos",
        processingQueue: "En Procesamiento",
        totalSources: "Fuentes Totales",
        acceptedSources: "Fuentes Aceptadas",
        draftsReady: "Borradores Listos",
        viewAll: "Ver todo",
        filter: "Filtrar",
        platform: "Plataforma",
        advanced: "Avanzado",
        dateAdded: "Fecha añadida",
        category: "Categoría",
        duration: "Duración",
        all: "Todo",
        processed: "Procesado",
        processing: "Procesando",
        unprocessed: "Sin procesar",
        run: "Ejecutar",
        export: "Exportar",
        decisionRationale: "Justificación de la Decisión",
        generateEvaluate: "Generar Borrador para Evaluar",
        pipelineExplanation: "El pipeline convierte la fuente en un borrador final, que luego se califica para la densidad de ideas.",
        pipelineStages: "Etapas del Pipeline",
        processingLog: "Registro de Procesamiento",
        allStagesComplete: "Todas las etapas del pipeline completadas.",
        sourceProcessed: "Esta fuente ha sido procesada y exportada completamente.",
        briefExplanation: "Este informe modifica explícitamente cómo el LLM redacta y cómo el QA Editorial evalúa la pieza.",
        resumePipeline: "Reanudar Pipeline",
        runPipelineToEvaluate: "Ejecute el pipeline hasta 'Evaluar Borrador' para generar una puntuación.",
        score: "Puntuación de Borrador",
        pending: "Pendiente",
        published: "Publicado",
        ingested: "Ingerido",
        search: "Buscar",
        noSourcesFound: "No se encontraron fuentes",
        noSourcesDescription: "Intente ajustar sus filtros o consulta de búsqueda.",
        viewSources: "Ver Fuentes",
        quickImport: "Importación Rápida",
        dates: "Fechas",
        actions: "Acciones",
        today: "Hoy",
        yesterday: "Ayer",
        last7Days: "Últimos 7 días",
        qualScore: "QUAL SCORE"
    },
    FR: {
        overview: "Aperçu",
        sources: "Sources",
        exports: "Centre d'Exportation",
        library: "Bibliothèque",
        settings: "Paramètres",
        importSource: "Importer Source",
        importFromDevice: "Importer de l'appareil",
        searchPlaceholder: "Rechercher ou coller URL...",
        monitorSources: "Surveiller les sources et les brouillons.",
        recentSources: "Sources Récentes",
        readyDrafts: "Brouillons Prêts",
        processingQueue: "En Cours",
        totalSources: "Total des Sources",
        acceptedSources: "Sources Acceptées",
        draftsReady: "Brouillons Prêts",
        viewAll: "Voir tout",
        filter: "Filtrer",
        platform: "Plateforme",
        advanced: "Avancé",
        dateAdded: "Date d'ajout",
        category: "Catégorie",
        duration: "Durée",
        all: "Tout",
        processed: "Traité",
        processing: "En cours",
        unprocessed: "Non traité",
        run: "Exécuter",
        export: "Exporter",
        decisionRationale: "Justification de la Décision",
        generateEvaluate: "Générer le Brouillon pour Évaluer",
        pipelineExplanation: "Le pipeline convertit la source en brouillon final, qui est ensuite noté pour la densité d'idées.",
        pipelineStages: "Étapes du Pipeline",
        processingLog: "Journal de Traitement",
        allStagesComplete: "Toutes les étapes du pipeline sont terminées.",
        sourceProcessed: "Cette source a été entièrement traitée et exportée.",
        briefExplanation: "Ce briefing modifie explicitement la manière dont l'IA rédige et dont le QA éditorial évalue la pièce.",
        resumePipeline: "Reprendre le Pipeline",
        runPipelineToEvaluate: "Exécutez le pipeline via 'Évaluer le brouillon' pour générer un score.",
        score: "Score du Brouillon",
        pending: "En attente",
        published: "Publié",
        ingested: "Ingéré",
        search: "Chercher",
        noSourcesFound: "Aucune source trouvée",
        noSourcesDescription: "Essayez d'ajuster vos filtres ou votre recherche.",
        viewSources: "Voir les Sources",
        quickImport: "Import Rapide",
        dates: "Dates",
        actions: "Actions",
        today: "Aujourd'hui",
        yesterday: "Hier",
        last7Days: "Les 7 derniers jours",
        qualScore: "QUAL SCORE"
    },
    DE: {
        overview: "Übersicht",
        sources: "Quellen",
        exports: "Exportzentrum",
        library: "Bibliothek",
        settings: "Einstellungen",
        importSource: "Quelle Importieren",
        importFromDevice: "Vom Gerät importieren",
        searchPlaceholder: "Themen suchen oder URL...",
        monitorSources: "Quellen und Entwürfe überwachen.",
        recentSources: "Aktuelle Quellen",
        readyDrafts: "Bereite Entwürfe",
        processingQueue: "In Bearbeitung",
        totalSources: "Quellen Gesamt",
        acceptedSources: "Akzeptierte Quellen",
        draftsReady: "Entwürfe Bereit",
        viewAll: "Alle ansehen",
        filter: "Filter",
        platform: "Plattform",
        advanced: "Erweitert",
        dateAdded: "Datum hinzugefügt",
        category: "Kategorie",
        duration: "Dauer",
        all: "Alle",
        processed: "Verarbeitet",
        processing: "Wird verarbeitet",
        unprocessed: "Unverarbeitet",
        run: "Ausführen",
        export: "Exportieren",
        decisionRationale: "Entscheidungsbegründung",
        generateEvaluate: "Entwurf zur Bewertung generieren",
        pipelineExplanation: "Die Pipeline konvertiert die Quelle in einen endgültigen Entwurf, der dann auf Insight-Dichte bewertet wird.",
        pipelineStages: "Pipeline-Stufen",
        processingLog: "Verarbeitungsprotokoll",
        allStagesComplete: "Alle Pipeline-Stufen abgeschlossen.",
        sourceProcessed: "Diese Quelle wurde vollständig verarbeitet und exportiert.",
        briefExplanation: "Dieser Briefing modifiziert explizit, wie das LLM entwirft und wie die redaktionelle Qualitätssicherung das Stück bewertet.",
        resumePipeline: "Pipeline fortsetzen",
        runPipelineToEvaluate: "Führen Sie die Pipeline bis zur 'Entwurfsbewertung' aus, um eine Punktzahl zu generieren.",
        score: "Entwurfspunktzahl",
        pending: "Ausstehend",
        published: "Veröffentlicht",
        ingested: "Eingelesen",
        search: "Suche",
        noSourcesFound: "Keine Quellen gefunden",
        noSourcesDescription: "Passen Sie Ihre Filter oder Suchanfrage an.",
        viewSources: "Quellen anzeigen",
        quickImport: "Schnellimport",
        dates: "Daten",
        actions: "Aktionen",
        today: "Heute",
        yesterday: "Gestern",
        last7Days: "Letzte 7 Tage",
        qualScore: "QUAL SCORE"
    },
    YO: {
        overview: "Ìgbéyẹ̀wò",
        sources: "Àwọn Orísun",
        exports: "Ilé Ìjájáde",
        library: "Àká Ìmọ̀",
        settings: "Ètò",
        importSource: "Kó Orísun Wọlé",
        importFromDevice: "Kó wọlé láti ẹ̀rọ",
        searchPlaceholder: "Wá àkọlé tàbí lẹ́ mọ́ URL...",
        monitorSources: "Ìbojútó àwọn orísun àti iṣẹ́.",
        recentSources: "Àwọn Orísun Tuntun",
        readyDrafts: "Ìwé Tí Ó Setán",
        processingQueue: "Ìṣiṣẹ́ Lọ́wọ́",
        totalSources: "Àpapọ̀ Orísun",
        acceptedSources: "Orísun Tí A Gbà",
        draftsReady: "Ìwé Tí Ó Setán",
        viewAll: "Wò ó gbogbo",
        filter: "Yọ̀rọ̀",
        platform: "Pèpéle",
        advanced: "Atunṣe Gíga",
        dateAdded: "Ọjọ́ Tí A Fi Kún Un",
        category: "Ìpín",
        duration: "Àkókò",
        all: "Gbogbo",
        processed: "Tí A Ti Ṣiṣẹ́ Lé",
        processing: "Ìṣiṣẹ́ Lọ́wọ́",
        unprocessed: "Tí A Kò Tíì Ṣiṣẹ́ Lé",
        run: "Ṣiṣẹ́",
        export: "Jáde",
        decisionRationale: "Ìpinn Ìpinn",
        generateEvaluate: "Ìpilẹ̀ṣẹ̀ Ìwé fún Ìgbéléwọ̀n",
        pipelineExplanation: "Ìṣètò náà yí orísun padà sí ìwé ìkẹyìn, tí a óò wá gbe yẹ̀ wò fún kókó ọ̀rọ̀.",
        pipelineStages: "Àwọn Ìpele Ìṣètò",
        processingLog: "Àkọsílẹ̀ Ìṣiṣẹ́",
        allStagesComplete: "Gbogbo ìpele ìṣètò ti parí.",
        sourceProcessed: "A ti ṣiṣẹ́ lórí orísun yìí pátápátá, a sì ti gbé e jáde.",
        briefExplanation: "Ìsọfúnni yìí ń yí bí LLM ṣe ń kọ̀wé àti bí QA ṣe ń gbé iṣẹ́ náà yẹ̀ wò padà.",
        resumePipeline: "Tẹ̀síwájú nínú Ìṣètò",
        runPipelineToEvaluate: "Ṣiṣẹ́ ìpele náà dé 'Gbé Ìwé Yẹ̀wò' láti gba máàkì.",
        score: "Máàkì Ìwé",
        pending: "Ìdúró",
        published: "Tí A Tẹ̀ Jáde",
        ingested: "Tí A Kó Wọlé",
        search: "Wá",
        noSourcesFound: "A kò rí orísun kankan",
        noSourcesDescription: "Gbìyànjú láti tún àyẹ̀ wò rẹ ṣe.",
        viewSources: "Wo Àwọn Orísun",
        quickImport: "Ìrọ̀rùn Kíkó Wọlé",
        dates: "Àwọn Ọjọ́",
        actions: "Àwọn Ìṣiṣẹ́",
        today: "Lónìí",
        yesterday: "Àná",
        last7Days: "Ọjọ́ 7 Tí Ó Kojá",
        qualScore: "QUAL SCORE"
    }
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [lang, setLang] = useState<Language>('EN')

    const t = (key: string) => {
        return translations[lang][key] || key
    }

    return (
        <LanguageContext.Provider value={{ lang, setLang, t }}>
            {children}
        </LanguageContext.Provider>
    )
}

export function useLanguage() {
    const context = useContext(LanguageContext)
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider')
    }
    return context
}
